chore: use the Engine API from containerd-shim-wasm crate
deislabs/containerd-wasm-shims pull request #148
Opened 2023-09-11 18:47 UTC by Mossaka

This commits updates to use the latest API from the `containerd-shim-wasm` crate. It follows the PR https://github.com/containerd/runwasi/pull/293

FYI: @jprendes

2023-09-12 13:19 UTC, jprendes requested changes
Most of the comments are just suggestion. The main thing that *needs* fixing is that the default `can_handle` is not suitable for most of the shims (it might be ok for lunatic).

Could you rename the `executor.rs` files to `engine.rs`?

I think many of the crates dependencies can be dropped now, just to take some examples from lunatic's Cargo.toml:
* libcontainer
* nix
* serde
* serde_json
* thiserror
* libc
* chrono
* oci-spec
* utils
* clap (needs removing the `derive(Args)` in `common.rs`)

But all shims could use a little clean up.

Also I believe the `utils` crate be removed.

2023-09-12 13:19 UTC, jprendes commented on containerd-shim-wws-v1/src/executor.rs
>          }
```suggestion
        rt.block_on(self.wasm_exec_async(path, routes))?
```

2023-09-19 13:26 UTC, Mossaka commented on containerd-shim-lunatic-v1/src/executor.rs
>              crate::executor::exec(cmd).await
Done.

2023-09-19 13:34 UTC, Mossaka commented on containerd-shim-slight-v1/src/executor.rs
>  use containerd_shim_wasm::sandbox::Stdio;
Will follow up with another PR

2023-09-19 13:40 UTC, Mossaka commented on containerd-shim-lunatic-v1/src/executor.rs
> +impl Engine for LunaticEngine {
Yes, lunatic shim requires a wasm entrypoint

2023-09-19 13:40 UTC, Mossaka commented on containerd-shim-spin-v1/src/executor.rs
> +impl Engine for SpinEngine {
Done

2023-09-19 13:41 UTC, Mossaka commented on containerd-shim-wws-v1/src/executor.rs
> +};
Done.

2023-09-19 14:02 UTC, Mossaka commented
Thanks for your careful review of this PR! @jprendes 

I have resolved all your comments.

2023-09-20 08:35 UTC, jprendes approved these changes
LGTM!

2023-09-21 11:38 UTC, merged