feat(slight-shim): mount the shim's resolv.conf to host's
deislabs/containerd-wasm-shims pull request #22
Opened 2022-10-04 00:13 UTC by Mossaka

This PR mounts the shim's resolv.conf to host's, so that the shim can use host's nameserver to do dns resolution. A consequence of this PR is that we can use outbound-http in our shim, and thus each http handler can read/write to external services such as AWS DynamoDB.

2022-10-04 13:58 UTC, devigned commented
@Mossaka I thought we hand DNS resolution working by chroot'ing to the rootfs dir. Was that not the case?

2022-10-04 14:08 UTC, cpuguy83 commented
We ran into an issue with that due to missing ca certs in the container rootfs.

2022-10-04 14:23 UTC, devigned commented
> We ran into an issue with that due to missing ca certs in the container rootfs.

Would it be better to mount the CA certs or to include the CA certs in the image?

2022-10-04 22:14 UTC, cpuguy83 commented on images/slight/src/main.rs
> +    println!("request body: {:?}", request.body);
Did you still want this here?

2022-10-04 22:24 UTC, devigned requested changes

2022-10-04 22:24 UTC, devigned commented on deployments/workloads/slight/workload.yaml
> +          image: docker.io/mossaka/slight-try3:awsdynamodb
We want to have an image reference similar to: https://github.com/deislabs/containerd-wasm-shims/blob/cb07e66d03625918cd37c22b93c6b760133f609e/deployments/workloads/spin/workload.yaml#L18.

2022-10-04 22:24 UTC, devigned commented on images/slight/slightfile.toml
> +[[capability]]
For the simple case for an example workload, I think we would like to limit functionality to capabilities that do not need secrets.

2022-10-05 17:38 UTC, devigned commented on images/slight/slightfile.toml
> +[[capability]]
Perhaps, use filesystem.

2022-10-05 18:22 UTC, merged